# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/EmbeddedVitis/custom_ip/user_led/user_led.srcs/sources_1/bd/user_led/ip/user_led_processing_system7_0_0/user_led_processing_system7_0_0.xci
# IP: The module: 'user_led_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/EmbeddedVitis/custom_ip/user_led/user_led.gen/sources_1/bd/user_led/ip/user_led_processing_system7_0_0/user_led_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'user_led_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/EmbeddedVitis/custom_ip/user_led/user_led.srcs/sources_1/bd/user_led/ip/user_led_processing_system7_0_0/user_led_processing_system7_0_0.xci
# IP: The module: 'user_led_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/EmbeddedVitis/custom_ip/user_led/user_led.gen/sources_1/bd/user_led/ip/user_led_processing_system7_0_0/user_led_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'user_led_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
