# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/EmbeddedVitis/gpio_mio_interrupt/gpio_mio_interrupt.srcs/sources_1/bd/gpio_mio_interrupt/ip/gpio_mio_interrupt_processing_system7_0_0/gpio_mio_interrupt_processing_system7_0_0.xci
# IP: The module: 'gpio_mio_interrupt_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/EmbeddedVitis/gpio_mio_interrupt/gpio_mio_interrupt.gen/sources_1/bd/gpio_mio_interrupt/ip/gpio_mio_interrupt_processing_system7_0_0/gpio_mio_interrupt_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'gpio_mio_interrupt_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/EmbeddedVitis/gpio_mio_interrupt/gpio_mio_interrupt.srcs/sources_1/bd/gpio_mio_interrupt/ip/gpio_mio_interrupt_processing_system7_0_0/gpio_mio_interrupt_processing_system7_0_0.xci
# IP: The module: 'gpio_mio_interrupt_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/EmbeddedVitis/gpio_mio_interrupt/gpio_mio_interrupt.gen/sources_1/bd/gpio_mio_interrupt/ip/gpio_mio_interrupt_processing_system7_0_0/gpio_mio_interrupt_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'gpio_mio_interrupt_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
