# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/user_led.xdc

# Block Designs: bd/user_led/user_led.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_led || ORIG_REF_NAME==user_led} -quiet] -quiet

# IP: bd/user_led/ip/user_led_processing_system7_0_0/user_led_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_led_processing_system7_0_0 || ORIG_REF_NAME==user_led_processing_system7_0_0} -quiet] -quiet

# IP: bd/user_led/ip/user_led_breath_led_ip_0_0/user_led_breath_led_ip_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_led_breath_led_ip_0_0 || ORIG_REF_NAME==user_led_breath_led_ip_0_0} -quiet] -quiet

# IP: bd/user_led/ip/user_led_auto_pc_0/user_led_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_led_auto_pc_0 || ORIG_REF_NAME==user_led_auto_pc_0} -quiet] -quiet

# IP: bd/user_led/ip/user_led_ps7_0_axi_periph_0/user_led_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_led_ps7_0_axi_periph_0 || ORIG_REF_NAME==user_led_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/user_led/ip/user_led_rst_ps7_0_50M_0/user_led_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_led_rst_ps7_0_50M_0 || ORIG_REF_NAME==user_led_rst_ps7_0_50M_0} -quiet] -quiet

# XDC: d:/EmbeddedVitis/custom_ip/user_led/user_led.gen/sources_1/bd/user_led/user_led_ooc.xdc
