# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/axi_gpio2.xdc

# Block Designs: bd/axi_gpio2/axi_gpio2.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_gpio2 || ORIG_REF_NAME==axi_gpio2} -quiet] -quiet

# IP: bd/axi_gpio2/ip/axi_gpio2_processing_system7_0_0/axi_gpio2_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_gpio2_processing_system7_0_0 || ORIG_REF_NAME==axi_gpio2_processing_system7_0_0} -quiet] -quiet

# IP: bd/axi_gpio2/ip/axi_gpio2_axi_gpio_0_0/axi_gpio2_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_gpio2_axi_gpio_0_0 || ORIG_REF_NAME==axi_gpio2_axi_gpio_0_0} -quiet] -quiet

# IP: bd/axi_gpio2/ip/axi_gpio2_auto_pc_0/axi_gpio2_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_gpio2_auto_pc_0 || ORIG_REF_NAME==axi_gpio2_auto_pc_0} -quiet] -quiet

# IP: bd/axi_gpio2/ip/axi_gpio2_ps7_0_axi_periph_0/axi_gpio2_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_gpio2_ps7_0_axi_periph_0 || ORIG_REF_NAME==axi_gpio2_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/axi_gpio2/ip/axi_gpio2_rst_ps7_0_50M_0/axi_gpio2_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_gpio2_rst_ps7_0_50M_0 || ORIG_REF_NAME==axi_gpio2_rst_ps7_0_50M_0} -quiet] -quiet

# XDC: d:/EmbeddedVitis/axi_gpio2/axi_gpio2.gen/sources_1/bd/axi_gpio2/axi_gpio2_ooc.xdc
