# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/EmbeddedVitis/axi_gpio2/axi_gpio2.srcs/sources_1/bd/axi_gpio2/ip/axi_gpio2_auto_pc_0/axi_gpio2_auto_pc_0.xci
# IP: The module: 'axi_gpio2_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/EmbeddedVitis/axi_gpio2/axi_gpio2.gen/sources_1/bd/axi_gpio2/ip/axi_gpio2_auto_pc_0/axi_gpio2_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_gpio2_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/EmbeddedVitis/axi_gpio2/axi_gpio2.srcs/sources_1/bd/axi_gpio2/ip/axi_gpio2_auto_pc_0/axi_gpio2_auto_pc_0.xci
# IP: The module: 'axi_gpio2_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/EmbeddedVitis/axi_gpio2/axi_gpio2.gen/sources_1/bd/axi_gpio2/ip/axi_gpio2_auto_pc_0/axi_gpio2_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_gpio2_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
